version: '3'
services:
    web:
        # image: manheok/flask-users-test
        build: .
        ports:
            - "5001:5001"
        # volumes:
        #     - ./flask_users:/code
        depends_on:
            - mongodb
            - redis
    mongodb:
        image: mongo
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
    worker:
        build: .
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
        entrypoint: ["celery"]
        command: ['-A', 'flask_users.tasks', 'worker', '-l', 'debug']
        depends_on:
            - redis
            - mongodb
    redis:
        image: redis
        ports:
            - 6379:6379

